pipeline {
    agent any
    
    stages {
        stage("git") {
            steps {
                git branch: 'main', credentialsId: '6e070d7b-950d-4c64-9818-2419b11f3210', url: 'https://github.com/venky0712/maven-dev.git'
            }
        }
        stage("build") {
            def mvnhome = tool name: 'maven', type: 'maven'
            steps {
                sh "${mvnhome}/mvn clean install"
            }
        }
    }
}
